/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { listPets } from "../funcs/list-pets.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class SDK extends ClientSDK {
  /**
   * List all pets
   */
  async listPets(
    options?: RequestOptions,
  ): Promise<Array<models.Pet>> {
    return unwrapAsync(listPets(
      this,
      options,
    ));
  }
}
