/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the petstore-sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx listPets.example.ts
 */

import { Petstore } from "petstore-sdk";

const petstore = new Petstore();

async function main() {
  const result = await petstore.listPets();

  console.log(result);
}

main().catch(console.error);
