/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Pet = {
  id: number;
  name: string;
};

/** @internal */
export const Pet$inboundSchema: z.ZodMiniType<Pet, unknown> = z.object({
  id: types.number(),
  name: types.string(),
});

export function petFromJSON(
  jsonString: string,
): SafeParseResult<Pet, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Pet$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Pet' from JSON`,
  );
}
